---
groups:
- name: nats-release
  jobs:
  - run-bosh-job-spec-tests
  - smoke-tests-and-cats
  - ship-what
  - create-final-release
- name: bump-go
  jobs:
  - upgrade-go1.x

resources:
- name: golang-release-latest
  type: git
  source:
    branch: master
    tag_filter: v*
    uri: https://github.com/bosh-packages/golang-release.git

- name: nats-release
  type: git
  source:
    ignore_paths:
      - .final_builds/**
      - config/**
      - releases/**
      - ci
    branch: develop
    private_key: ((routing-ci-runtime-ssh-key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: nats-release-ci
  type: git
  source:
    paths:
      - ci
    branch: develop
    private_key: ((routing-ci-runtime-ssh-key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: routing-release-ci
  type: git
  source:
    paths:
      - ci/tasks
    branch: develop
    uri: https://github.com/cloudfoundry/routing-release

- name: nats-release-master
  type: git
  source:
    branch: release
    private_key: ((routing-ci-runtime-ssh-key.private_key))
    uri: git@github.com:cloudfoundry/nats-release.git

- name: cf-deployment
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: networking-oss-deployments
  type: git
  source:
    branch: main
    private_key: ((routing-ci-runtime-ssh-key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: we-dont-use-vars-files
  type: git
  source:
    branch: main
    private_key: ((routing-ci-runtime-ssh-key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: cf-acceptance-tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: weekly
  type: time
  icon: clock
  source:
    interval: '168h'  # 1 week

jobs:
- name: upgrade-go1.x
  plan:
  - in_parallel:
    - get: nats-release
    - get: golang-release-latest
      trigger: true
    - get: nats-release-ci
      params:
        submodules: none
  - task: upgrade
    file: nats-release-ci/ci/tasks/upgrade-package-in-release/task.yml
    params:
      RELEASE: release
      PACKAGE: golang-1-linux
      BRANCH: develop
      GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY: ((gcp_nats_blobstore_service_account_key))
    input_mapping:
      release: nats-release
      package-release: golang-release-latest
  - task: save-golang-version-to-file
    file: nats-release-ci/ci/tasks/save-golang-version-to-file/task.yml
    params:
      BRANCH: develop
    input_mapping:
      release: modified-release
  - put: nats-release
    params:
      repository: modified-release
      rebase: true

- name: run-bosh-job-spec-tests
  plan:
    - in_parallel:
      - get: nats-release
        trigger: true
      - get: weekly
        trigger: true
    - task: run-bosh-job-spec-tests
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: ruby
            tag: '2.7'
        inputs:
          - name: nats-release
        run:
          path: /bin/bash
          args:
            - -c
            - |
              cd nats-release/spec
              bundle install
              rspec .

- name: smoke-tests-and-cats
  plan:
  - in_parallel:
    - do:
      - get: routing-release-ci
        params:
          submodules: none
      - task: claim-cf-deployment-environment
        file: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task.yml
        params:
          ENVIRONMENT_TYPE: cf-deployment
          ENVIRONMENT_NOTES: nats-cf-deployment-cats
          TOOLSMITHS_API_TOKEN: ((networking-toolsmiths-api-token))
    - get: cf-acceptance-tests
    - get: nats-release-ci
    - get: networking-oss-deployments
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: nats-release
      trigger: true
      passed: [run-bosh-job-spec-tests]
    - get: we-dont-use-vars-files
    - get: weekly
      trigger: true
      passed: [run-bosh-job-spec-tests]
  - task: write-lb-cert-to-credhub
    file: routing-release-ci/ci/tasks/write-lb-cert-to-credhub/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: merge-ops-files
    file: routing-release-ci/ci/tasks/merge-ops-files/task.yml
    input_mapping:
      source1: nats-release-ci
    params:
      SOURCE1_DIR: example-manifests/ops-files
  - task: redeploy-nats-release
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      release: nats-release
      ops-files: merged-operations
      vars-files: we-dont-use-vars-files
    params:
      OPS_FILES: |
        add-lb-ca-cert.yml
        use-compiled-releases.yml
        scale-for-cats.yml
        smoke-tests.yml
        disable-iso-seg-smoke-tests.yml
        fix-nats-tls-server.yml
  - task: run-smoke-tests
    file: nats-release-ci/ci/tasks/run-errand-nats-release/task.yml
    params:
      DEPLOYMENT_NAME: cf
      ERRAND_NAME: smoke-tests
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: create-integration-config
    file: nats-release-ci/ci/tasks/create-integration-configs/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
    params:
      ENABLE_ISOLATION_SEGMENT_TESTS: false
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      integration-configs: created-integration-configs
    params:
      CATS_INTEGRATION_CONFIG_FILE: cats_integration_config.json
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  - task: run-cats
    input_mapping:
      integration-config: updated-integration-configs
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    params:
      CONFIG_FILE_PATH: cats_integration_config.json
  - task: release-pooled-environment
    file: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task.yml
    params:
      TOOLSMITHS_API_TOKEN: ((networking-toolsmiths-api-token))

- name: ship-what
  serial: true
  plan:
  - in_parallel:
    - get: nats-release
      params:
        submodules: all
      trigger: true
      passed: [smoke-tests-and-cats]
    - get: nats-release-ci
      params:
        submodules: none
  - task: build-release-notes
    file: nats-release-ci/ci/tasks/build-release-notes/task.yml
    input_mapping:
      master-release: nats-release
    params:
      TRACKER_API_TOKEN: ((tracker_api_token))
  - task: print-bosh-job-spec-diff
    file: nats-release-ci/ci/tasks/print-bosh-job-spec-diff/task.yml
    input_mapping:
      master-release: nats-release

- name: create-final-release
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: nats-release-ci
      params:
        submodules: none
    - get: nats-release
      passed: [ship-what]
    - get: nats-release-master
  - task: create-final-release
    file: nats-release-ci/ci/tasks/create-final-nats-release/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
    params:
      MASTER_BRANCH: release
      RELEASE_NAME: nats
      GCP_NATS_BLOBSTORE_SERVICE_ACCOUNT_KEY: ((gcp_nats_blobstore_service_account_key))
  - put: nats-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v
  - task: merge-master-into-develop
    file: nats-release-ci/ci/tasks/merge-nats-release-master-into-develop/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
    params:
      MASTER_BRANCH: release
  - put: nats-release
    params:
      repository: final-release-repo
