---
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

platform: linux

inputs:
  - name: nats-release-ci
  - name: master-release

run:
  path: nats-release-ci/ci/tasks/print-bosh-job-spec-diff/task

params:
  SOURCE_DIR: master-release
